spring:
  datasource:
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY:bXlzZWNyZXRrZXlteXNlY3JldGtleW15c2VjcmV0a2V5bXlzZWNyZXRrZXk=}

app:
  auth:
    google-client-id: ${GOOGLE_CLIENT_ID:665052367365-sh62qn5f2e1i1dd0cigd3kjq3jrv3f84.apps.googleusercontent.com}
